In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L:
    print(e)

1
2
3


In [5]:
for e in A:
    print(e)

1
2
3


In [6]:
L.append(4)

In [7]:
L

[1, 2, 3, 4]

In [8]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [9]:
L + [5]

[1, 2, 3, 4, 5]

In [10]:
A + np.array(4)

array([5, 6, 7])

In [11]:
A + np.array([4,5,6])

array([5, 7, 9])

In [12]:
A + np.array([4,5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [13]:
2 * A

array([2, 4, 6])

In [14]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [17]:
# no numpy allowed vecotr manipulation

L2 = []
for e in L:
    L2.append(e + 3)

In [18]:
L2

[4, 5, 6, 7]

In [19]:
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

In [20]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [21]:
L2 = []
for e in L:
    L2.append(e**2)

In [22]:
L2

[1, 4, 9, 16]

In [23]:
A**2

array([1, 4, 9], dtype=int32)

In [24]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [25]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [26]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

### The Dot Product

In [27]:
a = np.array([1,2])
b = np.array([3,4])

In [28]:
dot = 0
for e, f in zip(a,b):
    dot += e *f
dot

11

In [29]:
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]
dot

11

In [30]:
a * b

array([3, 8])

In [31]:
np.sum(a * b)

11

In [32]:
(a * b).sum()

11

In [33]:
np.dot(a,b)

11

In [34]:
a.dot(b)

11

In [35]:
a @ b

11

In [36]:
## exploring connection to alternate definition

In [37]:
amag = np.sqrt((a*a).sum())
amag

2.23606797749979

In [38]:
np.linalg.norm(a)

2.23606797749979

In [39]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [40]:
cosangle

0.9838699100999074

In [41]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

### Matrices

In [44]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [45]:
L[0]

[1, 2]

In [46]:
L[0][1]

2

In [47]:
A = np.array([[1,2],[3,4]])

In [48]:
A

array([[1, 2],
       [3, 4]])

In [49]:
A[0][1]

2

In [50]:
A[0,1]

2

In [51]:
A[:,0]

array([1, 3])

In [52]:
A.T

array([[1, 3],
       [2, 4]])

In [53]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [54]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [55]:
B =np.array([[1,2,3],[4,5,6]])

In [56]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [58]:
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [59]:
np.linalg.det(A)

-2.0000000000000004

In [60]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [61]:
np.linalg.inv(A).dot(A)

array([[ 1.00000000e+00,  4.44089210e-16],
       [-5.55111512e-17,  1.00000000e+00]])

In [62]:
np.trace(A)

5

In [63]:
np.diag(A)

array([1, 4])

In [64]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [65]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [66]:
Lam, V = np.linalg.eig(A)[]
V[:,0] * Lam[0] ==A @V[:,0]

SyntaxError: invalid syntax (87061465.py, line 1)

In [67]:
V[:,0] * Lam[0], A @ V[:,0]

NameError: name 'V' is not defined

In [68]:
## IF you put in a vector, you get a matrix, if you put in a matrix you get a vector
np.diag(A)

array([1, 4])

In [69]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [70]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [71]:
Lam, V = np.linalg.eig(A)

In [72]:
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [73]:
V[:,0] * Lam[0] , A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [74]:
# Correct way to check in np if two are the same
np.allclose(V[:,0] * Lam[0] , A @ V[:,0])

True